#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=10
STOP=98

uci_apply_defaults() {
	. /lib/functions/system.sh

	cd /etc/uci-defaults || return 0
	files="$(ls)"
	[ -z "$files" ] && return 0
	mkdir -p /tmp/.uci
	for file in $files; do
		( . "./$(basename $file)" ) && rm -f "$file"
	done
    sleep 10
	uci set network.LTE=interface
	uci set network.LTE.proto='qmi'
	uci set network.LTE.device='/dev/cdc-wdm0'
	uci set network.LTE.apn='cmnet'
    uci set network.LTE.ifname='wwan0'
    #uci set network.lan.ifname='at0 eth0'
	#uci set network.WIFI_LAN=interface
	#uci set network.WIFI_LAN.proto='static'
	#uci set network.WIFI_LAN.ipaddr='192.168.2.1'
	#uci set network.WIFI_LAN.netmask='255.255.255.0'
	#uci set network.WIFI_LAN.ifname='at0'
	uci commit
}

boot() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /var/tmp
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
	touch /var/log/wtmp
	touch /var/log/lastlog
	touch /tmp/resolv.conf.auto
	ln -sf /tmp/resolv.conf.auto /tmp/resolv.conf
	grep -q debugfs /proc/filesystems && /bin/mount -o noatime -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	/sbin/kmodloader

	[ ! -f /etc/config/wireless ] && {
		# compat for brcm47xx and mvebu
		sleep 1
	}

	/bin/config_generate
	uci_apply_defaults
	
	# temporary hack until configd exists
	/sbin/reload_config
}
